import type { Metadata } from 'next'

import '@/app/globals.css'
import { Inter as FontSans } from 'next/font/google'

import { cn } from '@/lib/utils'
import PageHeader from '../components/Layout/PageHeader'
import SidebarLayout from '../components/Layout/SideBarLayout'

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={cn('min-h-screen bg-background font-sans antialiased', fontSans.variable)}>
        <PageHeader />
        <div className="grid grid-cols-[auto,1fr] gap-10 w-full">
          <div className="">
            <SidebarLayout />
          </div>
          <div className="flex justify-center my-6 mx-3">{children}</div>
        </div>
      </body>
    </html>
  )
}
